"use client";

import { useState } from "react";
import Link from "next/link";
import {
  Activity,
  AlertTriangle,
  ArrowRight,
  BadgeCheck,
  BookOpenCheck,
  Building2,
  CalendarClock,
  Check,
  CheckCircle2,
  Download,
  Filter,
  GitBranch,
  Info,
  LockKeyhole,
  MessageSquareText,
  Network,
  PackageCheck,
  Play,
  Plus,
  Search,
  ShieldCheck,
  ShoppingBag,
  TrendingUp,
  UserCheck,
  Users,
  WalletCards,
  Waves,
  X,
} from "lucide-react";
import { DataTable, KpiCard, PageIntro, ProgressBar, SectionHeader, SegmentedBars, StatusBadge, buttonStyles } from "@/components/ui";
import { auditEvents, demoMembers, demoOrders, demoProducts, feedbackAnnotations, getMemberChildren } from "@/lib/demo-data";
import { calculateAnnualDistribution, calculateOrderAllocation, processSettlement, type PerformanceEvent } from "@/lib/compensation";
import { formatNumber, formatTwd, memberStatusLabels, orderStatusLabels, productStatusLabels, shortDate } from "@/lib/format";
import type { DemoAccount, MemberStatus, ProductStatus } from "@/types/domain";

const eventInputs: PerformanceEvent[] = demoOrders.slice(0, 18).map((order) => ({
  idempotencyKey: `order:${order.id}:settlement`,
  memberId: order.memberId,
  amountTwd: order.amountTwd,
  type: "ORDER",
  sourceId: order.id,
  settlementMonth: "2026-08",
  planVersion: "PLAN-2026-08",
}));

const settlementDemo = processSettlement(eventInputs, demoMembers, { m001: 3900, m002: 4000, m003: 5300, m004: 8000, m005: 9500 });

export function AdminViews({ section }: { section: string; account: DemoAccount }) {
  if (section === "members") return <AdminMembers />;
  if (section === "organization") return <AdminOrganization />;
  if (section === "vendors") return <AdminVendors />;
  if (section === "products") return <AdminProducts />;
  if (section === "orders") return <AdminOrders />;
  if (section === "plan") return <AdminPlan />;
  if (section === "settlements") return <AdminSettlements />;
  if (section === "water-pool") return <AdminWaterPool />;
  if (section === "annual") return <AdminAnnual />;
  if (section === "reports") return <AdminReports />;
  if (section === "audit") return <AdminAudit />;
  if (section === "feedback") return <AdminFeedback />;
  return <AdminOverview />;
}

const statusTone = (status: MemberStatus) => status === "NORMAL" ? "normal" : status === "FROZEN" || status === "SUSPENDED" ? "warning" : "danger";
const productTone = (status: ProductStatus) => status === "PUBLISHED" || status === "APPROVED" ? "normal" : status === "RETURNED" ? "danger" : status === "PENDING" ? "warning" : "neutral";

function AdminOverview() {
  const active = demoMembers.filter((member) => member.status === "NORMAL").length;
  const waterTotal = settlementDemo.waterPool.reduce((sum, entry) => sum + entry.amountTwd, 0);
  return <div className="animate-enter"><PageIntro title="營運管理總覽" description="200 人固定制度情境 · 2026 年 8 月制度版本 · 資料更新於剛剛" actions={<><Link href="/admin/reports" className={buttonStyles.secondary}><Download className="size-4" />匯出摘要</Link><Link href="/admin/settlements" className={buttonStyles.gold}><Play className="size-4" />月結預演</Link></>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><KpiCard label="模擬會員" value="200" helper={`${active} 名狀態正常`} trend={{ value: "+8", direction: "up" }} icon={Users} /><KpiCard label="本月業績值" value={formatTwd(1842600)} helper="依正式結算月份歸屬" trend={{ value: "+9.4%", direction: "up" }} icon={TrendingUp} tone="gold" /><KpiCard label="待結算訂單" value="42" helper="其中 9 筆明日到期" icon={ShoppingBag} tone="blue" /><KpiCard label="大水庫累計" value={formatTwd(286740 + waterTotal)} helper="介紹獎金與十代缺位分列" icon={Waves} tone="stone" /><KpiCard label="待處理標註" value="1" helper="本輪共 3 則回饋" icon={MessageSquareText} tone="green" /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><section className="surface min-w-0 rounded-xl p-5"><SectionHeader eyebrow="PERFORMANCE" title="業績與獎金分配" description="每月制度版本獨立計算" action={<Link href="/admin/reports" className={buttonStyles.ghost}>查看報表<ArrowRight className="size-4" /></Link>} /><SegmentedBars values={[118, 142, 136, 161, 154, 172, 168, 194, 181, 216, 202, 228]} labels={["9月", "10月", "11月", "12月", "1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月"]} active={11} /><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["準備金", "10%", "#57534e"], ["介紹獎金", "9%", "#8a6107"], ["十代獎金", "45%", "#b8892d"], ["商品＋毛利", "36%", "#157348"]].map(([label, value, color]) => <div key={label} className="rounded-lg bg-stone-50 p-3"><span className="mb-2 block size-2 rounded-full" style={{ background: color }} /><p className="font-data text-lg font-semibold">{value}</p><p className="text-[0.625rem] text-stone-500">{label}</p></div>)}</div></section><section className="surface min-w-0 rounded-xl p-5"><SectionHeader eyebrow="SYSTEM HEALTH" title="本月檢核狀態" /><div className="space-y-3">{[["固定 200 人種子資料", 100, "已鎖定"], ["組織關係完整性", 100, "通過"], ["訂單逐筆資金守恆", 100, "通過"], ["月結驗算覆蓋", 92, "18 / 20 情境"], ["頁面回饋處理", 67, "2 / 3 完成"]].map(([label, value, status]) => <div key={String(label)}><div className="mb-1 flex justify-between text-xs"><span className="font-medium">{label}</span><span className="font-data text-stone-500">{status}</span></div><ProgressBar value={value as number} tone={value === 100 ? "green" : "gold"} /></div>)}</div><div className="mt-5 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-xs leading-5 text-emerald-800"><CheckCircle2 className="mr-1 inline size-4" />目前無資金守恆或重複發獎異常。</div></section></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><section className="surface overflow-hidden rounded-xl"><div className="p-5 pb-2"><SectionHeader eyebrow="RECENT ACTIVITY" title="最新稽核活動" action={<Link href="/admin/audit" className={buttonStyles.ghost}>全部紀錄</Link>} /></div><AuditRows limit={4} /></section><section className="surface overflow-hidden rounded-xl"><div className="p-5 pb-2"><SectionHeader eyebrow="FEEDBACK" title="示範回饋" action={<Link href="/admin/feedback" className={buttonStyles.ghost}>集中處理</Link>} /></div><div className="divide-y divide-stone-100">{feedbackAnnotations.map((item) => <div key={item.id} className="flex gap-3 px-5 py-3"><span className="mt-1 grid size-8 shrink-0 place-items-center rounded-lg bg-[#f8efd9] text-[#8a6107]"><MessageSquareText className="size-4" /></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><p className="truncate text-sm font-semibold">{item.targetLabel}</p><StatusBadge tone={item.status === "DONE" ? "normal" : item.status === "OPEN" ? "warning" : "info"}>{item.status === "DONE" ? "已完成" : item.status === "OPEN" ? "待處理" : "已回覆"}</StatusBadge></div><p className="mt-1 line-clamp-1 text-xs text-stone-500">{item.content}</p></div></div>)}</div></section></div>
  </div>;
}

function AdminMembers() {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("ALL");
  const shown = demoMembers.filter((member) => (status === "ALL" || member.status === status) && `${member.name}${member.memberNo}`.toLowerCase().includes(query.toLowerCase())).slice(0, 40);
  return <div className="animate-enter"><PageIntro title="會員管理" description="推薦關係建立後鎖定；特殊錯誤更正需最高權限並留下完整稽核紀錄。" actions={<button className={buttonStyles.gold}><Plus className="size-4" />新增合成會員</button>} /><div className="mb-4 grid gap-3 sm:grid-cols-3 xl:grid-cols-5"><KpiCard label="全部會員" value="200" helper="固定種子版本 V1" icon={Users} /><KpiCard label="正常" value={String(demoMembers.filter((m) => m.status === "NORMAL").length)} helper="正常登入與分潤" icon={UserCheck} tone="green" /><KpiCard label="凍結／停權" value={String(demoMembers.filter((m) => m.status === "FROZEN" || m.status === "SUSPENDED").length)} helper="獎金進暫存" icon={LockKeyhole} tone="gold" /><KpiCard label="退出／失效" value={String(demoMembers.filter((m) => m.status === "EXITED" || m.status === "INVALID").length)} helper="位置保留、不壓縮" icon={AlertTriangle} tone="stone" /><KpiCard label="12,000 方案" value={String(demoMembers.filter((m) => m.planAmount === 12000).length)} helper="年度分配資格母體" icon={BadgeCheck} tone="blue" /></div>
    <div className="surface mb-4 flex flex-col gap-3 rounded-xl p-3 sm:flex-row"><div className="flex min-h-11 flex-1 items-center gap-2 rounded-lg border border-stone-200 bg-white px-3"><Search className="size-4 text-stone-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="搜尋姓名或會員編號" /></div><select value={status} onChange={(event) => setStatus(event.target.value)} className="min-h-11 rounded-lg border border-stone-200 bg-white px-3 text-sm"><option value="ALL">全部狀態</option><option value="NORMAL">正常</option><option value="FROZEN">凍結</option><option value="SUSPENDED">停權</option><option value="EXITED">已退出</option><option value="INVALID">失效</option></select><button className={buttonStyles.secondary}><Filter className="size-4" />進階篩選</button></div>
    <section className="surface overflow-hidden rounded-xl"><DataTable headers={["會員", "方案", "推薦人", "有效直推", "可領代數", "加入日", "稅務旗標", "狀態", "操作"]} minWidth={1080}>{shown.map((member) => { const sponsor = demoMembers.find((item) => item.id === member.sponsorId); return <tr key={member.id} className="hover:bg-[#fbfaf8]"><td className="px-3 py-3"><p className="text-sm font-semibold">{member.name}</p><p className="font-data text-[0.625rem] text-stone-400">{member.memberNo}</p></td><td className="font-data px-3 py-3 text-sm">{formatTwd(member.planAmount)}</td><td className="px-3 py-3 text-sm">{sponsor?.name ?? "組織起點"}</td><td className="font-data px-3 py-3 text-sm">{member.directCount}</td><td className="px-3 py-3"><span className="font-data font-semibold text-[#8a6107]">{member.unlockedGenerations}</span><span className="text-xs text-stone-400"> / 10</span></td><td className="px-3 py-3 text-xs text-stone-500">{shortDate(member.joinedAt)}</td><td className="px-3 py-3"><div className="flex gap-1">{member.incomeTaxApplicable && <StatusBadge tone="warning">稅</StatusBadge>}{member.nhiApplicable && <StatusBadge tone="info">健保</StatusBadge>}{!member.incomeTaxApplicable && !member.nhiApplicable && "—"}</div></td><td className="px-3 py-3"><StatusBadge tone={statusTone(member.status)}>{memberStatusLabels[member.status]}</StatusBadge></td><td className="px-3 py-3"><button className="min-h-10 rounded-lg px-3 text-xs font-semibold text-[#8a6107] hover:bg-[#f8efd9]">查看</button></td></tr>;})}</DataTable><div className="border-t border-stone-100 px-4 py-3 text-xs text-stone-500">顯示 {shown.length} / 200 筆測試會員</div></section>
  </div>;
}

function AdminOrganization() {
  const roots = demoMembers.filter((member) => member.depth <= 2).slice(0, 28);
  return <div className="animate-enter"><PageIntro title="全域組織查詢" description="查看固定推薦樹、會員資格快照及各代獎金去向；退出與失效節點保留原位置。" actions={<button className={buttonStyles.secondary}><Download className="size-4" />匯出組織</button>} /><div className="grid gap-4 xl:grid-cols-[320px_1fr]"><aside className="surface min-w-0 rounded-xl p-4"><label className="flex min-h-11 items-center gap-2 rounded-lg border border-stone-200 px-3"><Search className="size-4 text-stone-400" /><input className="w-full text-sm outline-none" placeholder="會員編號或姓名" /></label><div className="mt-4 space-y-1"><p className="px-2 text-[0.6875rem] font-bold tracking-wide text-stone-400">組織概況</p>{[["組織總人數", "200"], ["最大深度", `${Math.max(...demoMembers.map((m) => m.depth))} 代`], ["空位／不足代", "38"], ["退出／失效位置", String(demoMembers.filter((m) => m.status === "EXITED" || m.status === "INVALID").length)]].map(([label, value]) => <div key={label} className="flex items-center justify-between rounded-lg px-2 py-2.5 text-sm hover:bg-stone-50"><span>{label}</span><span className="font-data font-semibold">{value}</span></div>)}</div><div className="mt-4 rounded-lg bg-[#fbf4e4] p-3 text-xs leading-5 text-[#795f2c]"><Info className="mr-1 inline size-3.5" />獎金由下單會員向上追溯；本圖由上往下顯示推薦關係。</div></aside><section className="surface min-h-[650px] overflow-auto rounded-xl p-6"><div className="min-w-[820px]"><div className="flex flex-col items-center"><div className="rounded-xl border-2 border-[#a16207] bg-[#fbf4e4] px-8 py-4 text-center"><p className="text-lg font-semibold">{demoMembers[0].name}</p><p className="font-data text-[0.625rem] text-stone-500">{demoMembers[0].memberNo} · 組織起點</p></div><div className="h-8 w-px bg-[#bfa45e]" /><div className="grid w-full grid-cols-4 gap-4 border-t border-[#bfa45e] pt-8">{getMemberChildren(demoMembers[0].id).slice(0, 4).map((member) => <div key={member.id} className="relative"><div className="absolute -top-8 left-1/2 h-8 w-px bg-[#bfa45e]" /><div className="rounded-xl border border-stone-200 bg-white p-3 text-center shadow-sm"><p className="font-semibold">{member.name}</p><p className="font-data text-[0.625rem] text-stone-400">{member.memberNo}</p><div className="mt-2 flex justify-center"><StatusBadge tone={statusTone(member.status)}>{memberStatusLabels[member.status]}</StatusBadge></div></div><div className="mt-3 space-y-2">{roots.filter((item) => item.sponsorId === member.id).slice(0, 3).map((child) => <div key={child.id} className={`rounded-lg border p-2 text-center ${child.status === "EXITED" || child.status === "INVALID" ? "border-dashed border-red-200 bg-red-50" : "border-stone-200 bg-stone-50"}`}><p className="text-xs font-semibold">{child.name}</p><p className="font-data text-[0.5625rem] text-stone-400">{child.memberNo}</p></div>)}</div></div>)}</div></div></div></section></div></div>;
}

function AdminVendors() {
  return <div className="animate-enter"><PageIntro title="廠商管理" description="廠商是平台供應商與履約出貨方；會員交易窗口仍為平台公司。" actions={<button className={buttonStyles.gold}><Plus className="size-4" />新增廠商</button>} /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 10 }, (_, index) => { const stock = demoProducts.filter((p) => p.vendorId === `v${String(index + 1).padStart(2, "0")}`).reduce((sum, p) => sum + p.stock, 0); return <article key={index} className="surface min-w-0 rounded-xl p-4"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-lg bg-[#f8efd9] text-[#8a6107]"><Building2 className="size-5" /></span><StatusBadge tone={index === 7 ? "warning" : "normal"}>{index === 7 ? "待補件" : "合作中"}</StatusBadge></div><h2 className="mt-4 font-semibold">經典合作廠商 {String(index + 1).padStart(2, "0")}</h2><p className="font-data mt-1 text-[0.6875rem] text-stone-400">V{String(index + 1).padStart(5, "0")} · 統編 8{index}369392</p><div className="mt-4 grid grid-cols-2 gap-2 text-center"><div className="rounded-lg bg-stone-50 p-2"><p className="font-data font-semibold">{demoProducts.filter((p) => p.vendorId === `v${String(index + 1).padStart(2, "0")}`).length}</p><p className="text-[0.625rem] text-stone-400">商品</p></div><div className="rounded-lg bg-stone-50 p-2"><p className="font-data font-semibold">{stock}</p><p className="text-[0.625rem] text-stone-400">庫存</p></div></div></article>;})}</div></div>;
}

function AdminProducts() {
  const [reviewed, setReviewed] = useState<string[]>([]);
  return <div className="animate-enter"><PageIntro title="商品審核" description="流程：草稿 → 待審核 → 退回修改／審核通過 → 已上架 → 下架。" /><section className="surface overflow-hidden rounded-xl"><DataTable headers={["商品", "廠商", "售價／成本", "庫存", "點數", "目前狀態", "審核操作"]} minWidth={940}>{demoProducts.map((product) => { const approved = reviewed.includes(product.id); return <tr key={product.id} className="hover:bg-[#fbfaf8]"><td className="px-3 py-3"><p className="text-sm font-semibold">{product.name}</p><p className="font-data text-[0.625rem] text-stone-400">{product.sku}</p></td><td className="font-data px-3 py-3 text-xs">{product.vendorId.toUpperCase()}</td><td className="px-3 py-3"><p className="font-data text-sm">{formatTwd(product.priceTwd)}</p><p className="font-data text-[0.625rem] text-stone-400">成本 {formatTwd(product.costTwd)}</p></td><td className="font-data px-3 py-3 text-sm">{product.stock}</td><td className="px-3 py-3">{product.pointsAllowed ? <Check className="size-4 text-emerald-600" /> : <X className="size-4 text-stone-300" />}</td><td className="px-3 py-3"><StatusBadge tone={approved ? "normal" : productTone(product.status)}>{approved ? "審核通過" : productStatusLabels[product.status]}</StatusBadge></td><td className="px-3 py-3">{product.status === "PENDING" && !approved ? <div className="flex gap-1"><button onClick={() => setReviewed((value) => [...value, product.id])} className="min-h-10 rounded-lg bg-emerald-50 px-3 text-xs font-semibold text-emerald-700 hover:bg-emerald-100">通過</button><button className="min-h-10 rounded-lg bg-red-50 px-3 text-xs font-semibold text-red-700 hover:bg-red-100">退回</button></div> : <button className="min-h-10 rounded-lg px-3 text-xs font-semibold text-[#8a6107] hover:bg-[#f8efd9]">查看</button>}</td></tr>;})}</DataTable></section></div>;
}

function AdminOrders() {
  return <div className="animate-enter"><PageIntro title="訂單管理" description="平台建立訂單、廠商依通知出貨；退換貨期結束後才可進入正式結算。" actions={<button className={buttonStyles.secondary}><Download className="size-4" />匯出訂單</button>} /><section className="surface overflow-hidden rounded-xl"><DataTable headers={["訂單", "會員", "方案金額", "廠商", "日期", "狀態", "可結算日", "操作"]} minWidth={980}>{demoOrders.map((order) => { const member = demoMembers.find((m) => m.id === order.memberId) ?? demoMembers[0]; return <tr key={order.id} className="hover:bg-[#fbfaf8]"><td className="font-data px-3 py-3 text-xs font-semibold">{order.orderNo}</td><td className="px-3 py-3"><p className="text-sm font-medium">{member.name}</p><p className="font-data text-[0.625rem] text-stone-400">{member.memberNo}</p></td><td className="font-data px-3 py-3 text-sm">{formatTwd(order.amountTwd)}</td><td className="font-data px-3 py-3 text-xs">{order.vendorId.toUpperCase()}</td><td className="px-3 py-3 text-xs text-stone-500">{shortDate(order.placedAt)}</td><td className="px-3 py-3"><StatusBadge tone={order.status === "SETTLED" ? "normal" : order.status === "SHIPPED" ? "info" : "warning"}>{orderStatusLabels[order.status]}</StatusBadge></td><td className="px-3 py-3 text-xs text-stone-500">09/{String((Number(order.id.slice(1)) % 20) + 1).padStart(2, "0")}</td><td className="px-3 py-3"><button className="min-h-10 rounded-lg px-3 text-xs font-semibold text-[#8a6107] hover:bg-[#f8efd9]">追蹤</button></td></tr>;})}</DataTable></section></div>;
}

function AdminPlan() {
  const allocation = calculateOrderAllocation(2000);
  return <div className="animate-enter"><PageIntro title="制度版本管理" description="制度以月份為單位；本月修改建立為下月版本，已結算歷史永不回溯。" actions={<button className={buttonStyles.gold}><Plus className="size-4" />建立下月版本</button>} /><div className="grid gap-4 xl:grid-cols-[1fr_360px]"><section className="surface min-w-0 rounded-xl p-5"><div className="flex flex-col gap-3 border-b border-stone-100 pb-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[0.6875rem] font-bold tracking-[.15em] text-[#8a6107]">ACTIVE VERSION</p><h2 className="mt-1 text-xl font-semibold">PLAN-2026-08</h2><p className="mt-1 text-xs text-stone-500">生效月份：2026 年 8 月 · 已鎖定</p></div><StatusBadge tone="normal">目前生效</StatusBadge></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["營運／稅務準備金", "10%"], ["業績值", "90%"], ["介紹獎金／業績值", "10%"], ["每代組織獎金", "5%"], ["最高代數", "10 代"], ["循環門檻", "$4,000"], ["現金切分", "$2,000"], ["點數切分", "2,000 點"], ["年度分配", "2%"]].map(([label, value]) => <div key={label} className="rounded-lg border border-stone-200 bg-stone-50 p-3"><p className="text-[0.6875rem] text-stone-500">{label}</p><p className="font-data mt-1 text-lg font-semibold">{value}</p></div>)}</div><div className="mt-6"><SectionHeader eyebrow="PLANS" title="會員方案與代數" /><DataTable headers={["方案", "商品數", "初始代數", "每有效直推", "最高代數"]} minWidth={580}>{[[2000, 1, 3, "+1 代", 10], [4000, 2, 5, "+1 代", 10], [12000, 6, 10, "直接開滿", 10]].map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${cell}-${index}`} className={`px-3 py-3 text-sm ${index === 0 ? "font-data font-semibold" : ""}`}>{index === 0 ? formatTwd(cell as number) : cell}</td>)}</tr>)}</DataTable></div></section><aside className="space-y-4"><section className="rounded-xl bg-[#1c1917] p-5 text-white"><p className="text-[0.6875rem] font-bold tracking-[.15em] text-[#d8b961]">2,000 元資金正推</p><div className="mt-5 space-y-3">{[["準備金", allocation.reserveTwd], ["介紹獎金", allocation.referralBudgetTwd], ["十代獎金", allocation.generationBudgetTwd], ["商品成本", allocation.productCostTwd], ["基礎營運毛利", allocation.operatingMarginTwd]].map(([label, amount]) => <div key={String(label)} className="flex items-center justify-between text-sm"><span className="text-white/55">{label}</span><span className="font-data font-semibold">{formatTwd(amount as number)}</span></div>)}</div><div className="mt-5 flex items-center gap-2 rounded-lg bg-emerald-500/10 p-3 text-xs text-emerald-300"><CheckCircle2 className="size-4" />金額守恆：100%</div></section><section className="surface min-w-0 rounded-xl p-4"><p className="flex items-center gap-2 text-sm font-semibold"><CalendarClock className="size-4 text-[#8a6107]" />待生效版本</p><div className="mt-3 rounded-lg bg-[#fbf4e4] p-3"><p className="font-data text-sm font-semibold">PLAN-2026-09</p><p className="mt-1 text-xs text-[#795f2c]">草稿 · 9 月 1 日生效</p></div></section></aside></div></div>;
}

function AdminSettlements() {
  const [status, setStatus] = useState<"PREVIEW" | "RUNNING" | "DONE">("PREVIEW");
  const totalOrders = settlementDemo.allocations.reduce((sum, item) => sum + item.allocation.amountTwd, 0);
  const bonusTotal = settlementDemo.bonuses.reduce((sum, item) => sum + item.amountTwd, 0);
  const waterTotal = settlementDemo.waterPool.reduce((sum, item) => sum + item.amountTwd, 0);
  function run() { setStatus("RUNNING"); setTimeout(() => setStatus("DONE"), 900); }
  return <div className="animate-enter"><PageIntro title="月結批次" description="以正式結算月份套用制度版本與會員資格快照；事件鍵防止重複發放。" actions={<button onClick={run} disabled={status !== "PREVIEW"} className={`${buttonStyles.gold} disabled:opacity-60`}>{status === "RUNNING" ? <><span className="size-4 animate-spin rounded-full border-2 border-white/30 border-t-white" />計算中</> : status === "DONE" ? <><CheckCircle2 className="size-4" />預演完成</> : <><Play className="size-4" />執行預演</>}</button>} />
    <section className={`mb-4 rounded-xl border p-4 ${status === "DONE" ? "border-emerald-200 bg-emerald-50" : "border-[#ead59e] bg-[#fbf4e4]"}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><span className={`grid size-10 place-items-center rounded-lg ${status === "DONE" ? "bg-emerald-600 text-white" : "bg-[#8a6107] text-white"}`}>{status === "DONE" ? <CheckCircle2 className="size-5" /> : <BookOpenCheck className="size-5" />}</span><div className="flex-1"><p className="font-semibold">2026 年 8 月月結預演</p><p className="mt-0.5 text-xs text-stone-600">固定資料版本 V1 · PLAN-2026-08 · 不寫入正式流水</p></div><StatusBadge tone={status === "DONE" ? "normal" : status === "RUNNING" ? "warning" : "gold"}>{status === "DONE" ? "驗算通過" : status === "RUNNING" ? "處理中" : "待執行"}</StatusBadge></div></section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><KpiCard label="業績事件" value={formatNumber(settlementDemo.processedEventKeys.length)} helper={`${eventInputs.length} 筆訂單＋重銷`} icon={Activity} /><KpiCard label="事件訂單金額" value={formatTwd(totalOrders)} helper="包含即刻重銷業績" icon={ShoppingBag} tone="blue" /><KpiCard label="會員獎金" value={formatTwd(bonusTotal)} helper={`${settlementDemo.bonuses.length} 筆分類流水`} icon={WalletCards} tone="green" /><KpiCard label="進大水庫" value={formatTwd(waterTotal)} helper={`${settlementDemo.waterPool.length} 筆原因分類`} icon={Waves} tone="stone" /><KpiCard label="4,000 元循環" value={formatNumber(settlementDemo.cycles.length)} helper="已建立唯一重銷事件" icon={GitBranch} tone="gold" /></div>
    <section className="surface mt-4 overflow-hidden rounded-xl"><div className="p-5 pb-2"><SectionHeader eyebrow="IDEMPOTENT EVENTS" title="事件處理結果" description="相同事件鍵重新送入會被忽略" /></div><DataTable headers={["事件鍵", "類型", "來源會員", "金額", "業績值", "獎金筆數", "水庫筆數", "結果"]} minWidth={980}>{settlementDemo.allocations.slice(0, 14).map(({ eventKey, allocation }, index) => <tr key={eventKey}><td className="font-data px-3 py-3 text-[0.6875rem]">{eventKey}</td><td className="px-3 py-3"><StatusBadge tone={eventKey.startsWith("resale") ? "gold" : "info"}>{eventKey.startsWith("resale") ? "重銷" : "訂單"}</StatusBadge></td><td className="font-data px-3 py-3 text-xs">{eventKey.startsWith("resale") ? eventKey.split(":")[1] : eventInputs[index]?.memberId ?? "—"}</td><td className="font-data px-3 py-3 text-sm">{formatTwd(allocation.amountTwd)}</td><td className="font-data px-3 py-3 text-sm">{formatNumber(allocation.performanceValue)}</td><td className="font-data px-3 py-3 text-sm">{settlementDemo.bonuses.filter((b) => b.eventKey === eventKey).length}</td><td className="font-data px-3 py-3 text-sm">{settlementDemo.waterPool.filter((w) => w.eventKey === eventKey).length}</td><td className="px-3 py-3"><StatusBadge tone={allocation.conserved ? "normal" : "danger"}>{allocation.conserved ? "守恆" : "異常"}</StatusBadge></td></tr>)}</DataTable></section>
  </div>;
}

function AdminWaterPool() {
  const categories = { UNPAID_REFERRAL: "未發介紹獎金", MISSING_GENERATION: "組織不足十代", INELIGIBLE_GENERATION: "退出／失效", LOCKED_GENERATION: "當月未開放代數" } as const;
  const totals = Object.fromEntries(Object.keys(categories).map((key) => [key, settlementDemo.waterPool.filter((entry) => entry.category === key).reduce((sum, entry) => sum + entry.amountTwd, 0)]));
  const total = Object.values(totals).reduce((sum, amount) => sum + Number(amount), 0);
  return <div className="animate-enter"><PageIntro title="大水庫獨立流水" description="介紹獎金與十代缺位分開分類；保留來源訂單、原應發會員、代數與未發原因。" actions={<button className={buttonStyles.secondary}><Download className="size-4" />匯出月報</button>} /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><KpiCard label="本次預演入池" value={formatTwd(total)} helper={`${settlementDemo.waterPool.length} 筆未發項目`} icon={Waves} /><KpiCard label="未發介紹獎金" value={formatTwd(Number(totals.UNPAID_REFERRAL))} helper="獨立類型，不與代數混淆" icon={UserCheck} tone="gold" /><KpiCard label="組織不足十代" value={formatTwd(Number(totals.MISSING_GENERATION))} helper="向上已無會員位置" icon={Network} tone="blue" /><KpiCard label="退出／失效位置" value={formatTwd(Number(totals.INELIGIBLE_GENERATION))} helper="位置保留但無人可領" icon={LockKeyhole} tone="stone" /><KpiCard label="未開放代數" value={formatTwd(Number(totals.LOCKED_GENERATION))} helper="依當月會員快照判定" icon={GitBranch} tone="green" /></div><section className="surface mt-4 overflow-hidden rounded-xl"><DataTable headers={["流水 ID", "來源事件", "來源會員", "原應發會員", "代數", "未發原因", "金額", "制度版本"]} minWidth={1040}>{settlementDemo.waterPool.slice(0, 40).map((entry) => <tr key={entry.id}><td className="font-data px-3 py-3 text-[0.625rem]">{entry.id.slice(-22)}</td><td className="font-data px-3 py-3 text-[0.625rem]">{entry.eventKey}</td><td className="font-data px-3 py-3 text-xs">{entry.sourceMemberId}</td><td className="font-data px-3 py-3 text-xs">{entry.expectedMemberId ?? "—"}</td><td className="font-data px-3 py-3 text-sm">{entry.generation ?? "—"}</td><td className="px-3 py-3"><StatusBadge tone={entry.category === "UNPAID_REFERRAL" ? "gold" : "neutral"}>{categories[entry.category]}</StatusBadge></td><td className="font-data px-3 py-3 text-sm font-semibold">{formatTwd(entry.amountTwd)}</td><td className="font-data px-3 py-3 text-[0.625rem]">{entry.planVersion}</td></tr>)}</DataTable></section></div>;
}

function AdminAnnual() {
  const eligible = demoMembers.filter((member) => member.planAmount === 12000 && member.status === "NORMAL");
  const [profit, setProfit] = useState(10_000_000);
  const result = calculateAnnualDistribution(profit, eligible.map((member) => member.id));
  return <div className="animate-enter"><PageIntro title="年度營餘分配" description="年度分配建立獨立批次與流水，不與每月十代分紅或 4,000 元循環混帳。" /><div className="grid gap-4 xl:grid-cols-[1fr_400px]"><section className="surface min-w-0 rounded-xl p-5"><SectionHeader eyebrow="ANNUAL DISTRIBUTION" title="2026 年度試算" /><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1.5 block text-sm font-semibold">完稅後可分配盈餘</span><input type="number" value={profit} onChange={(event) => setProfit(Number(event.target.value))} className="h-12 w-full rounded-lg border border-stone-200 px-3 font-data focus:border-[#a16207] focus:outline-none" /></label><label><span className="mb-1.5 block text-sm font-semibold">資格判定日</span><input type="date" defaultValue="2026-12-31" className="h-12 w-full rounded-lg border border-stone-200 px-3 font-data focus:border-[#a16207] focus:outline-none" /></label></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-stone-50 p-4"><p className="text-xs text-stone-500">提撥比例</p><p className="font-data mt-1 text-2xl font-semibold">2%</p></div><div className="rounded-xl bg-stone-50 p-4"><p className="text-xs text-stone-500">符合資格會員</p><p className="font-data mt-1 text-2xl font-semibold">{eligible.length}</p></div><div className="rounded-xl bg-[#fbf4e4] p-4"><p className="text-xs text-[#795f2c]">每位原始分配</p><p className="font-data mt-1 text-2xl font-semibold text-[#795307]">{formatTwd(result.perMemberTwd)}</p></div></div><button className={`${buttonStyles.gold} mt-5`}><Play className="size-4" />建立預覽批次</button></section><aside className="rounded-xl bg-[#1c1917] p-5 text-white"><p className="text-[0.6875rem] font-bold tracking-[.15em] text-[#d8b961]">FORMULA</p><p className="mt-4 text-sm leading-7 text-white/65">年度完稅後可分配盈餘 × 2%<br />÷ 當年度符合資格會員人數</p><div className="my-5 h-px bg-white/12" /><div className="space-y-3 text-sm"><div className="flex justify-between"><span className="text-white/45">年度分配池</span><span className="font-data">{formatTwd(result.poolTwd)}</span></div><div className="flex justify-between"><span className="text-white/45">整數餘額</span><span className="font-data">{formatTwd(result.remainderTwd)}</span></div></div><div className="mt-6 rounded-lg bg-white/6 p-3 text-xs leading-5 text-white/45"><Info className="mr-1 inline size-3.5" />本批次不進入每月 4,000 元循環；正式發放前仍需獨立審核。</div></aside></div></div>;
}

function AdminReports() {
  return <div className="animate-enter"><PageIntro title="營運報表" description="商城、會員、業績、獎金、大水庫與財務指標的示範彙整。" actions={<button className={buttonStyles.secondary}><Download className="size-4" />匯出報表包</button>} /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="訂單總額" value={formatTwd(2048000)} helper="本月 512 筆模擬訂單" icon={ShoppingBag} /><KpiCard label="已發會員獎金" value={formatTwd(1105920)} helper="介紹＋十代＋年度分配" icon={WalletCards} tone="green" /><KpiCard label="重銷轉換率" value="64.8%" helper="形成點數後 30 日內選品" icon={PackageCheck} tone="gold" /><KpiCard label="平均可領代數" value="7.2 代" helper="本月會員資格快照" icon={GitBranch} tone="blue" /></div><div className="mt-4 grid gap-4 xl:grid-cols-2"><section className="surface min-w-0 rounded-xl p-5"><SectionHeader eyebrow="ORDERS" title="每月訂單總額" /><SegmentedBars values={[112, 128, 146, 139, 158, 171, 166, 188, 201, 194, 217, 228]} labels={["9", "10", "11", "12", "1", "2", "3", "4", "5", "6", "7", "8"]} active={11} /></section><section className="surface min-w-0 rounded-xl p-5"><SectionHeader eyebrow="PLAN MIX" title="方案結構" /><div className="space-y-4">{[["2,000 元方案", demoMembers.filter((m) => m.planAmount === 2000).length, "gold"], ["4,000 元方案", demoMembers.filter((m) => m.planAmount === 4000).length, "blue"], ["12,000 元方案", demoMembers.filter((m) => m.planAmount === 12000).length, "green"]].map(([label, count, tone]) => <div key={String(label)}><div className="mb-1.5 flex justify-between text-sm"><span>{label}</span><span className="font-data font-semibold">{count} 人</span></div><ProgressBar value={count as number} max={200} tone={tone as "gold"} /></div>)}</div></section></div></div>;
}

function AuditRows({ limit = auditEvents.length }: { limit?: number }) {
  return <DataTable headers={["時間", "操作者", "動作", "目標", "結果"]} minWidth={680}>{auditEvents.slice(0, limit).map((event) => <tr key={event.id}><td className="px-3 py-3 text-xs text-stone-500">{shortDate(event.createdAt)}</td><td className="px-3 py-3 text-sm font-medium">{event.actor}</td><td className="px-3 py-3 text-sm">{event.action}</td><td className="font-data px-3 py-3 text-xs">{event.target}</td><td className="px-3 py-3"><StatusBadge tone={event.result === "SUCCESS" ? "normal" : "danger"}>{event.result === "SUCCESS" ? "成功" : "已阻擋"}</StatusBadge></td></tr>)}</DataTable>;
}

function AdminAudit() {
  return <div className="animate-enter"><PageIntro title="稽核紀錄" description="角色權限、制度變更、推薦關係更正及財務操作均留下不可覆寫的操作紀錄。" actions={<button className={buttonStyles.secondary}><Download className="size-4" />匯出稽核</button>} /><div className="grid gap-3 sm:grid-cols-3"><KpiCard label="本日操作" value="184" helper="4 種角色共 40 組帳號" icon={Activity} /><KpiCard label="敏感操作" value="12" helper="制度、財務與會員狀態" icon={ShieldCheck} tone="gold" /><KpiCard label="阻擋越權" value="3" helper="皆已記錄來源與角色" icon={LockKeyhole} tone="green" /></div><section className="surface mt-4 overflow-hidden rounded-xl"><AuditRows /></section></div>;
}

function AdminFeedback() {
  const [statuses, setStatuses] = useState<Record<string, string>>(Object.fromEntries(feedbackAnnotations.map((item) => [item.id, item.status])));
  return <div className="animate-enter"><PageIntro title="回饋標註中心" description="集中保存頁面、位置、提出者、日期、內容與處理狀態，避免意見散落在通訊軟體。" /><div className="grid gap-4 xl:grid-cols-[1fr_320px]"><section className="space-y-3">{feedbackAnnotations.map((item) => <article key={item.id} className="surface min-w-0 rounded-xl p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-[#f8efd9] text-[#8a6107]"><MessageSquareText className="size-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{item.targetLabel}</h2><StatusBadge tone={statuses[item.id] === "DONE" ? "normal" : statuses[item.id] === "OPEN" ? "warning" : "info"}>{statuses[item.id] === "DONE" ? "已完成" : statuses[item.id] === "OPEN" ? "待處理" : "已回覆"}</StatusBadge></div><p className="font-data mt-1 text-[0.6875rem] text-stone-400">{item.route}</p><p className="mt-3 text-sm leading-6 text-stone-700">{item.content}</p><p className="mt-3 text-xs text-stone-400">{item.author} · {shortDate(item.createdAt)}</p></div><select value={statuses[item.id]} onChange={(event) => setStatuses((value) => ({ ...value, [item.id]: event.target.value }))} className="min-h-10 rounded-lg border border-stone-200 bg-white px-3 text-xs"><option value="OPEN">待處理</option><option value="REPLIED">已回覆</option><option value="DONE">已完成</option></select></div></article>)}</section><aside className="surface h-fit rounded-xl p-5"><SectionHeader eyebrow="ROUND 1" title="第一輪回饋" /><div className="text-center"><div className="mx-auto grid size-24 place-items-center rounded-full border-[8px] border-[#e7dfcd] border-t-[#a16207]"><span className="font-data text-xl font-semibold">67%</span></div><p className="mt-4 text-sm font-semibold">2 / 3 已回覆或完成</p><p className="mt-1 text-xs text-stone-500">全部完成後可建立集中修改版本。</p></div><button className={`${buttonStyles.gold} mt-5 w-full`}>建立集中修改清單</button></aside></div></div>;
}
