"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { BadgeDollarSign, BookOpenCheck, CheckCircle2, CircleDollarSign, Download, FileBarChart, FileClock, Filter, Landmark, ReceiptText, Search, ShieldCheck, TrendingUp, WalletCards, Waves } from "lucide-react";
import { DataTable, KpiCard, PageIntro, ProgressBar, SectionHeader, SegmentedBars, StatusBadge, buttonStyles } from "@/components/ui";
import { demoMembers } from "@/lib/demo-data";
import { calculateWithdrawal } from "@/lib/compensation";
import { formatTwd } from "@/lib/format";
import type { DemoAccount } from "@/types/domain";

const withdrawalRows = demoMembers.slice(0, 18).map((member, index) => {
  const gross = [4000, 6000, 8000, 10000, 12000][index % 5];
  return { id: `WD-202608-${String(index + 1).padStart(4, "0")}`, member, ...calculateWithdrawal(gross, member), status: index < 8 ? "PENDING" : index < 13 ? "APPROVED" : "PAID" };
});

export function FinanceViews({ section }: { section: string; account: DemoAccount }) {
  if (section === "settlements") return <FinanceSettlements />;
  if (section === "withdrawals") return <FinanceWithdrawals />;
  if (section === "ledger") return <FinanceLedger />;
  if (section === "withholding") return <FinanceWithholding />;
  if (section === "water-pool") return <FinanceWaterPool />;
  if (section === "exports") return <FinanceExports />;
  return <FinanceOverview />;
}

function FinanceOverview() {
  return <div className="animate-enter"><PageIntro title="財務管理總覽" description="2026 年 8 月 · 獎金、扣繳、提領與人工匯款模擬" actions={<Link href="/finance/withdrawals" className={buttonStyles.gold}><BadgeDollarSign className="size-4" />處理 8 筆提領</Link>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><KpiCard label="本月應得獎金" value={formatTwd(1105920)} helper="介紹獎金＋十代獎金" trend={{ value: "+9.8%", direction: "up" }} icon={TrendingUp} /><KpiCard label="待結算獎金" value={formatTwd(186480)} helper="退換貨期或月結中" icon={BookOpenCheck} tone="gold" /><KpiCard label="待審核提領" value={formatTwd(withdrawalRows.slice(0, 8).reduce((sum, row) => sum + row.grossTwd, 0))} helper="8 筆會員申請" icon={WalletCards} tone="blue" /><KpiCard label="預估扣繳" value={formatTwd(withdrawalRows.reduce((sum, row) => sum + row.incomeTaxTwd + row.nhiTwd, 0))} helper="依會員測試旗標" icon={CircleDollarSign} tone="stone" /><KpiCard label="本月已模擬匯款" value={formatTwd(428000)} helper="76 筆已標記完成" icon={Landmark} tone="green" /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.12fr_.88fr]"><section className="surface min-w-0 rounded-xl p-5"><SectionHeader eyebrow="CASH FLOW" title="本月獎金與提領" /><SegmentedBars values={[22, 28, 31, 26, 38, 42, 36, 48, 44, 51, 47, 58]} labels={["1", "3", "5", "7", "9", "11", "13", "15", "17", "19", "21", "23"]} active={11} /><div className="mt-4 flex flex-wrap gap-4 text-xs"><span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-[#a16207]" />獎金入帳</span><span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-[#d8c59c]" />提領付款</span></div></section><section className="surface min-w-0 rounded-xl p-5"><SectionHeader eyebrow="MONTH CLOSE" title="8 月月結檢核" /><div className="space-y-4">{[["訂單狀態完整", 100], ["會員資格快照", 100], ["獎金資金守恆", 100], ["扣繳旗標確認", 92], ["提領人工匯款", 76]].map(([label, value]) => <div key={String(label)}><div className="mb-1.5 flex justify-between text-xs"><span>{label}</span><span className="font-data">{value}%</span></div><ProgressBar value={value as number} tone={value === 100 ? "green" : "gold"} /></div>)}</div></section></div>
    <section className="surface mt-4 overflow-hidden rounded-xl"><div className="p-5 pb-2"><SectionHeader eyebrow="PENDING WITHDRAWALS" title="待審核提領" action={<Link href="/finance/withdrawals" className={buttonStyles.ghost}>查看全部</Link>} /></div><WithdrawalTable rows={withdrawalRows.slice(0, 6)} /></section>
  </div>;
}

function FinanceSettlements() {
  const [approved, setApproved] = useState(false);
  return <div className="animate-enter"><PageIntro title="月結批次" description="財務確認批次總額、扣繳與會員實付；商業制度由管理員建立並鎖定。" /><section className="mb-4 rounded-xl border border-[#ead59e] bg-[#fbf4e4] p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><span className="grid size-12 place-items-center rounded-xl bg-[#8a6107] text-white"><BookOpenCheck className="size-6" /></span><div className="flex-1"><p className="font-semibold">SET-2026-08 · 2026 年 8 月月結</p><p className="mt-1 text-xs text-[#795f2c]">PLAN-2026-08 · 固定資料版本 V1 · 管理員預演已通過</p></div><StatusBadge tone={approved ? "normal" : "warning"}>{approved ? "財務已確認" : "待財務確認"}</StatusBadge></div></section><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="應結算訂單" value="142" helper="總額 $568,000" icon={ReceiptText} /><KpiCard label="會員獎金流水" value="1,294" helper="介紹、十代與循環" icon={FileClock} tone="blue" /><KpiCard label="大水庫流水" value="386" helper="逐筆記錄未發原因" icon={Waves} tone="stone" /><KpiCard label="淨應付會員" value={formatTwd(328410)} helper="本期新增現金獎金" icon={WalletCards} tone="green" /></div><section className="surface mt-4 rounded-xl p-5"><SectionHeader eyebrow="FINANCE CHECK" title="財務確認清單" /><div className="grid gap-3 md:grid-cols-2">{["訂單總額與業績值一致", "準備金與商品成本分列", "介紹獎金與十代獎金分列", "凍結／停權獎金進暫存", "大水庫原因分類完整", "重銷事件無重複鍵", "稅務旗標快照已保存", "歷史制度版本未被改寫"].map((item) => <label key={item} className="flex min-h-12 items-center gap-3 rounded-lg border border-stone-200 bg-stone-50 px-3 text-sm"><input type="checkbox" defaultChecked className="size-4 accent-[#8a6107]" />{item}</label>)}</div><button onClick={() => setApproved(true)} className={`${buttonStyles.gold} mt-5`}><CheckCircle2 className="size-4" />確認本批次</button></section></div>;
}

function WithdrawalTable({ rows, onApprove }: { rows: typeof withdrawalRows; onApprove?: (id: string) => void }) {
  return <DataTable headers={["申請編號", "會員", "總額", "所得稅", "補充保費", "實付", "狀態", "操作"]} minWidth={980}>{rows.map((row) => <tr key={row.id} className="hover:bg-[#fbfaf8]"><td className="font-data px-3 py-3 text-xs font-semibold">{row.id}</td><td className="px-3 py-3"><p className="text-sm font-medium">{row.member.name}</p><p className="font-data text-[0.625rem] text-stone-400">{row.member.memberNo}</p></td><td className="font-data px-3 py-3 text-sm">{formatTwd(row.grossTwd)}</td><td className="font-data px-3 py-3 text-sm text-red-700">−{formatTwd(row.incomeTaxTwd)}</td><td className="font-data px-3 py-3 text-sm text-red-700">−{formatTwd(row.nhiTwd)}</td><td className="font-data px-3 py-3 text-sm font-semibold text-emerald-700">{formatTwd(row.netTwd)}</td><td className="px-3 py-3"><StatusBadge tone={row.status === "PAID" ? "normal" : row.status === "APPROVED" ? "info" : "warning"}>{row.status === "PAID" ? "已付款" : row.status === "APPROVED" ? "已核准" : "待審核"}</StatusBadge></td><td className="px-3 py-3">{row.status === "PENDING" && onApprove ? <button onClick={() => onApprove(row.id)} className="min-h-10 rounded-lg bg-[#1c1917] px-3 text-xs font-semibold text-white">核准</button> : <button className="min-h-10 rounded-lg px-3 text-xs font-semibold text-[#8a6107] hover:bg-[#f8efd9]">明細</button>}</td></tr>)}</DataTable>;
}

function FinanceWithdrawals() {
  const [approved, setApproved] = useState<string[]>([]);
  const rows = withdrawalRows.map((row) => approved.includes(row.id) ? { ...row, status: "APPROVED" } : row);
  return <div className="animate-enter"><PageIntro title="提領審核" description="會員申請 → 財務審核 → 人工匯款 → 後台標記完成。" actions={<button className={buttonStyles.secondary}><Download className="size-4" />匯出匯款清單</button>} /><div className="surface mb-4 flex flex-col gap-3 rounded-xl p-3 sm:flex-row"><div className="flex min-h-11 flex-1 items-center gap-2 rounded-lg border border-stone-200 bg-white px-3"><Search className="size-4 text-stone-400" /><input className="w-full text-sm outline-none" placeholder="搜尋申請編號或會員" /></div><select className="min-h-11 rounded-lg border border-stone-200 bg-white px-3 text-sm"><option>全部狀態</option><option>待審核</option><option>已核准</option><option>已付款</option></select><button className={buttonStyles.secondary}><Filter className="size-4" />扣繳旗標</button></div><section className="surface overflow-hidden rounded-xl"><WithdrawalTable rows={rows} onApprove={(id) => setApproved((value) => [...value, id])} /></section></div>;
}

function FinanceLedger() {
  const types = ["訂單準備金", "業績值", "直接推薦獎金", "十代獎金", "現金獎金", "購物點數", "大水庫", "平台營運毛利"];
  return <div className="animate-enter"><PageIntro title="財務分類流水" description="每筆流水保留來源事件、制度版本與相對應帳戶，歷史資料不可覆寫。" actions={<button className={buttonStyles.secondary}><Download className="size-4" />匯出 CSV</button>} /><section className="surface overflow-hidden rounded-xl"><DataTable headers={["流水 ID", "時間", "分類", "來源事件", "借方", "貸方", "制度版本", "狀態"]} minWidth={1060}>{Array.from({ length: 28 }, (_, index) => { const amount = [200, 1800, 180, 90, 2000, 2000, 90, 120][index % 8]; return <tr key={index}><td className="font-data px-3 py-3 text-[0.625rem]">LED-202608-{String(index + 1).padStart(6, "0")}</td><td className="px-3 py-3 text-xs text-stone-500">08/{String(26 - (index % 12)).padStart(2, "0")} {String(8 + (index % 9)).padStart(2, "0")}:20</td><td className="px-3 py-3 text-sm font-medium">{types[index % types.length]}</td><td className="font-data px-3 py-3 text-[0.625rem]">order:o{String((index % 18) + 1).padStart(4, "0")}:settlement</td><td className="font-data px-3 py-3 text-sm">{index % 2 === 0 ? formatTwd(amount) : "—"}</td><td className="font-data px-3 py-3 text-sm">{index % 2 !== 0 ? formatTwd(amount) : "—"}</td><td className="font-data px-3 py-3 text-[0.625rem]">PLAN-2026-08</td><td className="px-3 py-3"><StatusBadge tone="normal">已入帳</StatusBadge></td></tr>;})}</DataTable></section></div>;
}

function FinanceWithholding() {
  const [gross, setGross] = useState(30000);
  const [tax, setTax] = useState(true);
  const [nhi, setNhi] = useState(true);
  const calculation = useMemo(() => calculateWithdrawal(gross, { incomeTaxApplicable: tax, nhiApplicable: nhi }), [gross, tax, nhi]);
  return <div className="animate-enter"><PageIntro title="扣繳試算" description="依會員旗標與制度參數試算，不自動判定法定門檻或實際適用資格。" /><div className="grid gap-4 xl:grid-cols-[1fr_400px]"><section className="surface min-w-0 rounded-xl p-5"><SectionHeader eyebrow="WITHHOLDING FLAGS" title="試算輸入" /><label><span className="mb-1.5 block text-sm font-semibold">會員應得獎金</span><input type="number" value={gross} onChange={(event) => setGross(Math.max(1, Number(event.target.value)))} className="h-12 w-full rounded-lg border border-stone-200 px-3 font-data focus:border-[#a16207] focus:outline-none" /></label><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="flex min-h-16 items-center gap-3 rounded-xl border border-stone-200 p-4"><input type="checkbox" checked={tax} onChange={(event) => setTax(event.target.checked)} className="size-5 accent-[#8a6107]" /><div><p className="text-sm font-semibold">所得稅預扣</p><p className="text-xs text-stone-500">測試參數 10%</p></div></label><label className="flex min-h-16 items-center gap-3 rounded-xl border border-stone-200 p-4"><input type="checkbox" checked={nhi} onChange={(event) => setNhi(event.target.checked)} className="size-5 accent-[#8a6107]" /><div><p className="text-sm font-semibold">健保補充保費</p><p className="text-xs text-stone-500">測試參數 2.11%</p></div></label></div><div className="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-900">此處只驗證分類欄位與計算結果；正式營運前由會計確認門檻、所得類別與申報方式。</div></section><aside className="rounded-xl bg-[#1c1917] p-5 text-white"><p className="text-[0.6875rem] font-bold tracking-[.15em] text-[#d8b961]">PAYMENT RESULT</p><h2 className="mt-1 text-xl font-semibold">試算結果</h2><div className="mt-6 space-y-3 text-sm"><div className="flex justify-between"><span className="text-white/50">應得獎金</span><span className="font-data">{formatTwd(calculation.grossTwd)}</span></div><div className="flex justify-between"><span className="text-white/50">所得稅預扣</span><span className="font-data text-red-300">−{formatTwd(calculation.incomeTaxTwd)}</span></div><div className="flex justify-between"><span className="text-white/50">補充保費</span><span className="font-data text-red-300">−{formatTwd(calculation.nhiTwd)}</span></div></div><div className="my-5 h-px bg-white/12" /><div className="flex items-end justify-between"><span className="text-sm text-white/50">會員實付</span><span className="font-data text-3xl font-semibold text-[#e2c77f]">{formatTwd(calculation.netTwd)}</span></div></aside></div></div>;
}

function FinanceWaterPool() {
  return <div className="animate-enter"><PageIntro title="大水庫帳務" description="財務檢視入池、累計餘額與後續使用；商業原因由制度引擎逐筆提供。" actions={<button className={buttonStyles.secondary}><Download className="size-4" />匯出月報</button>} /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="期初餘額" value={formatTwd(245880)} helper="2026-08-01" icon={Waves} /><KpiCard label="本月入池" value={formatTwd(48620)} helper="326 筆分類流水" icon={TrendingUp} tone="gold" /><KpiCard label="本月使用" value={formatTwd(-7780)} helper="公告批次 POOL-08-02" icon={CircleDollarSign} tone="blue" /><KpiCard label="目前餘額" value={formatTwd(286720)} helper="截至 2026-08-26" icon={WalletCards} tone="green" /></div><section className="surface mt-4 overflow-hidden rounded-xl"><DataTable headers={["日期", "批次／事件", "類型", "來源分類", "收入", "支出", "餘額", "狀態"]} minWidth={900}>{Array.from({ length: 16 }, (_, index) => { const income = index % 5 === 4 ? 0 : [90, 180, 90, 450][index % 4]; const out = income === 0 ? 2000 : 0; return <tr key={index}><td className="px-3 py-3 text-xs text-stone-500">08/{String(26 - index).padStart(2, "0")}</td><td className="font-data px-3 py-3 text-[0.625rem]">{income ? `order:o${String(index + 1).padStart(4, "0")}` : "POOL-USE-08-02"}</td><td className="px-3 py-3"><StatusBadge tone={income ? "gold" : "info"}>{income ? "入池" : "使用"}</StatusBadge></td><td className="px-3 py-3 text-sm">{income ? ["未發介紹獎金", "組織不足十代", "未開放代數"][index % 3] : "定期公告用途"}</td><td className="font-data px-3 py-3 text-sm text-emerald-700">{income ? `+${formatTwd(income)}` : "—"}</td><td className="font-data px-3 py-3 text-sm text-red-700">{out ? `−${formatTwd(out)}` : "—"}</td><td className="font-data px-3 py-3 text-sm">{formatTwd(286720 - index * 850)}</td><td className="px-3 py-3"><StatusBadge tone="normal">已入帳</StatusBadge></td></tr>;})}</DataTable></section></div>;
}

function FinanceExports() {
  const reports = [["會員獎金分類明細", "CSV", "會員、獎金類型、代數、來源訂單、制度版本"], ["所得稅與補充保費試算", "XLSX", "應得、所得稅、補充保費與實付"], ["提領人工匯款清單", "CSV", "銀行測試資料、總額、扣款與實付"], ["大水庫月報", "XLSX", "入池來源、原因、使用與期末餘額"], ["月結驗算摘要", "PDF", "資金守恆、事件總數與異常檢核"], ["廠商結算資料", "CSV", "訂單、成本、調整與應付金額"]];
  return <div className="animate-enter"><PageIntro title="報表匯出" description="匯出檔案只包含固定合成測試資料，欄位結構可作為正式版確認基準。" /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{reports.map(([title, format, description]) => <article key={title} className="surface min-w-0 rounded-xl p-5"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-lg bg-[#f8efd9] text-[#8a6107]"><FileBarChart className="size-5" /></span><StatusBadge tone="neutral">{format}</StatusBadge></div><h2 className="mt-4 font-semibold">{title}</h2><p className="mt-1 min-h-10 text-xs leading-5 text-stone-500">{description}</p><button className={`${buttonStyles.secondary} mt-4 w-full`}><Download className="size-4" />產生測試報表</button></article>)}</div><section className="mt-4 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900"><ShieldCheck className="mr-2 inline size-4" />所有匯出動作會記錄操作者、條件、時間與檔案摘要，供稽核追蹤。</section></div>;
}
